version: '3.8'

services:
  fleetblox-ocr:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./sessions:/app/sessions
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped